version=0.1

[default.global.parameters]
stack_name = "hello-world"
region = "us-east-1"

[default.deploy.parameters]
s3_bucket = "<bucket name>"
template = "./infra-templates/master-template.yaml"
confirm_changeset = true
capabilities = [ "CAPABILITY_AUTO_EXPAND", "CAPABILITY_NAMED_IAM", "CAPABILITY_IAM" ]